TebLocalPlannerROS:
  odom_topic: odom

  teb_autosize: true
  dt_ref: 0.15
  dt_hysteresis: 0.05
  global_plan_overwrite_orientation: true
  allow_init_with_backwards_motion: true
  max_global_plan_lookahead_dist: 3.0
  force_reinit_new_goal_dist: 1.0
  force_reinit_new_goal_angular: 0.78
  feasibility_check_no_poses: 5
  exact_arc_length: true
  publish_feedback: false

  max_vel_x: 0.22
  max_vel_x_backwards: 0.08
  max_vel_y: 0.0
  max_vel_theta: 0.25
  acc_lim_x: 0.40
  acc_lim_y: 0.0
  acc_lim_theta: 0.80
  wheelbase: 0.41893
  cmd_angle_instead_rotvel: true
  is_footprint_dynamic: false

  footprint_model:
    type: polygon
    vertices:
      - [0.30, 0.18]
      - [0.30, -0.18]
      - [-0.30, -0.18]
      - [-0.30, 0.18]

  xy_goal_tolerance: 0.35
  yaw_goal_tolerance: 0.70
  free_goal_vel: false

  min_obstacle_dist: 0.16
  inflation_dist: 0.42
  dynamic_obstacle_inflation_dist: 0.48
  include_dynamic_obstacles: false
  include_costmap_obstacles: true
  legacy_obstacle_association: false
  obstacle_association_force_inclusion_factor: 1.5
  obstacle_association_cutoff_factor: 5.0
  costmap_obstacles_behind_robot_dist: 2.0
  obstacle_poses_affected: 20

  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.05
  weight_max_vel_x: 2.0
  weight_max_vel_y: 1.0
  weight_max_vel_theta: 3.0
  weight_acc_lim_x: 1.0
  weight_acc_lim_y: 1.0
  weight_acc_lim_theta: 8.0
  weight_kinematics_nh: 1000.0
  weight_kinematics_forward_drive: 15.0
  weight_kinematics_turning_radius: 50.0
  weight_optimaltime: 0.5
  weight_shortest_path: 0.5
  weight_obstacle: 60.0
  weight_inflation: 0.2
  weight_dynamic_obstacle: 50.0
  weight_dynamic_obstacle_inflation: 0.2
  weight_viapoint: 1.0
  weight_adapt_factor: 2.0

  global_plan_viapoint_sep: 0.80
  via_points_ordered: true

  enable_homotopy_class_planning: false
  enable_multithreading: true
  max_number_classes: 4
  selection_prefer_initial_plan: 0.9

  shrink_horizon_backup: true
  oscillation_recovery: true
