obstacle_range: 4.0
raytrace_range: 5.0
transform_tolerance: 0.5
max_obstacle_height: 1.5
footprint:
  - [0.34, 0.22]
  - [0.34, -0.22]
  - [-0.34, -0.22]
  - [-0.34, 0.22]
inflation_radius: 0.35
cost_scaling_factor: 5.0
observation_sources: laser_scan_sensor
laser_scan_sensor:
  sensor_frame: laser_link
  data_type: LaserScan
  topic: scan
  marking: true
  clearing: true
