GlobalPlanner:
  allow_unknown: false
  default_tolerance: 0.10
  use_dijkstra: false
  use_quadratic: true
  use_grid_path: false
  old_navfn_behavior: false
  lethal_cost: 253
  neutral_cost: 66
  cost_factor: 0.55
  publish_potential: false
  publish_scale: 100
